// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface AttendanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.AttendanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>string class_id = 2;</code>
   * @return The classId.
   */
  java.lang.String getClassId();
  /**
   * <code>string class_id = 2;</code>
   * @return The bytes for classId.
   */
  com.google.protobuf.ByteString
      getClassIdBytes();

  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
