// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface AttendanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.AttendanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool present = 1;</code>
   * @return The present.
   */
  boolean getPresent();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string recorded_time = 3;</code>
   * @return The recordedTime.
   */
  java.lang.String getRecordedTime();
  /**
   * <code>string recorded_time = 3;</code>
   * @return The bytes for recordedTime.
   */
  com.google.protobuf.ByteString
      getRecordedTimeBytes();
}
