// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

/**
 * Protobuf type {@code smartclassroom.EngagementResponse}
 */
public final class EngagementResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartclassroom.EngagementResponse)
    EngagementResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EngagementResponse.newBuilder() to construct.
  private EngagementResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EngagementResponse() {
    studentId_ = "";
    timestamp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EngagementResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_EngagementResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_EngagementResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.class, com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.Builder.class);
  }

  public static final int STUDENT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object studentId_;
  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  @java.lang.Override
  public java.lang.String getStudentId() {
    java.lang.Object ref = studentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentId_ = s;
      return s;
    }
  }
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudentIdBytes() {
    java.lang.Object ref = studentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTENTION_SCORE_FIELD_NUMBER = 2;
  private double attentionScore_;
  /**
   * <code>double attention_score = 2;</code>
   * @return The attentionScore.
   */
  @java.lang.Override
  public double getAttentionScore() {
    return attentionScore_;
  }

  public static final int PARTICIPATION_COUNT_FIELD_NUMBER = 3;
  private int participationCount_;
  /**
   * <code>int32 participation_count = 3;</code>
   * @return The participationCount.
   */
  @java.lang.Override
  public int getParticipationCount() {
    return participationCount_;
  }

  public static final int ENGAGEMENT_LEVEL_FIELD_NUMBER = 4;
  private int engagementLevel_;
  /**
   * <code>int32 engagement_level = 4;</code>
   * @return The engagementLevel.
   */
  @java.lang.Override
  public int getEngagementLevel() {
    return engagementLevel_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentId_);
    }
    if (java.lang.Double.doubleToRawLongBits(attentionScore_) != 0) {
      output.writeDouble(2, attentionScore_);
    }
    if (participationCount_ != 0) {
      output.writeInt32(3, participationCount_);
    }
    if (engagementLevel_ != 0) {
      output.writeInt32(4, engagementLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentId_);
    }
    if (java.lang.Double.doubleToRawLongBits(attentionScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, attentionScore_);
    }
    if (participationCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, participationCount_);
    }
    if (engagementLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, engagementLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nci.smartclassroom.smartclassroomsystem.EngagementResponse)) {
      return super.equals(obj);
    }
    com.nci.smartclassroom.smartclassroomsystem.EngagementResponse other = (com.nci.smartclassroom.smartclassroomsystem.EngagementResponse) obj;

    if (!getStudentId()
        .equals(other.getStudentId())) return false;
    if (java.lang.Double.doubleToLongBits(getAttentionScore())
        != java.lang.Double.doubleToLongBits(
            other.getAttentionScore())) return false;
    if (getParticipationCount()
        != other.getParticipationCount()) return false;
    if (getEngagementLevel()
        != other.getEngagementLevel()) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStudentId().hashCode();
    hash = (37 * hash) + ATTENTION_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAttentionScore()));
    hash = (37 * hash) + PARTICIPATION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getParticipationCount();
    hash = (37 * hash) + ENGAGEMENT_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getEngagementLevel();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nci.smartclassroom.smartclassroomsystem.EngagementResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartclassroom.EngagementResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartclassroom.EngagementResponse)
      com.nci.smartclassroom.smartclassroomsystem.EngagementResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_EngagementResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_EngagementResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.class, com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.Builder.class);
    }

    // Construct using com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      studentId_ = "";

      attentionScore_ = 0D;

      participationCount_ = 0;

      engagementLevel_ = 0;

      timestamp_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_EngagementResponse_descriptor;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.EngagementResponse getDefaultInstanceForType() {
      return com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.EngagementResponse build() {
      com.nci.smartclassroom.smartclassroomsystem.EngagementResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.EngagementResponse buildPartial() {
      com.nci.smartclassroom.smartclassroomsystem.EngagementResponse result = new com.nci.smartclassroom.smartclassroomsystem.EngagementResponse(this);
      result.studentId_ = studentId_;
      result.attentionScore_ = attentionScore_;
      result.participationCount_ = participationCount_;
      result.engagementLevel_ = engagementLevel_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nci.smartclassroom.smartclassroomsystem.EngagementResponse) {
        return mergeFrom((com.nci.smartclassroom.smartclassroomsystem.EngagementResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nci.smartclassroom.smartclassroomsystem.EngagementResponse other) {
      if (other == com.nci.smartclassroom.smartclassroomsystem.EngagementResponse.getDefaultInstance()) return this;
      if (!other.getStudentId().isEmpty()) {
        studentId_ = other.studentId_;
        onChanged();
      }
      if (other.getAttentionScore() != 0D) {
        setAttentionScore(other.getAttentionScore());
      }
      if (other.getParticipationCount() != 0) {
        setParticipationCount(other.getParticipationCount());
      }
      if (other.getEngagementLevel() != 0) {
        setEngagementLevel(other.getEngagementLevel());
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              studentId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 17: {
              attentionScore_ = input.readDouble();

              break;
            } // case 17
            case 24: {
              participationCount_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              engagementLevel_ = input.readInt32();

              break;
            } // case 32
            case 42: {
              timestamp_ = input.readStringRequireUtf8();

              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object studentId_ = "";
    /**
     * <code>string student_id = 1;</code>
     * @return The studentId.
     */
    public java.lang.String getStudentId() {
      java.lang.Object ref = studentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string student_id = 1;</code>
     * @return The bytes for studentId.
     */
    public com.google.protobuf.ByteString
        getStudentIdBytes() {
      java.lang.Object ref = studentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string student_id = 1;</code>
     * @param value The studentId to set.
     * @return This builder for chaining.
     */
    public Builder setStudentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string student_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudentId() {
      
      studentId_ = getDefaultInstance().getStudentId();
      onChanged();
      return this;
    }
    /**
     * <code>string student_id = 1;</code>
     * @param value The bytes for studentId to set.
     * @return This builder for chaining.
     */
    public Builder setStudentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentId_ = value;
      onChanged();
      return this;
    }

    private double attentionScore_ ;
    /**
     * <code>double attention_score = 2;</code>
     * @return The attentionScore.
     */
    @java.lang.Override
    public double getAttentionScore() {
      return attentionScore_;
    }
    /**
     * <code>double attention_score = 2;</code>
     * @param value The attentionScore to set.
     * @return This builder for chaining.
     */
    public Builder setAttentionScore(double value) {
      
      attentionScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double attention_score = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttentionScore() {
      
      attentionScore_ = 0D;
      onChanged();
      return this;
    }

    private int participationCount_ ;
    /**
     * <code>int32 participation_count = 3;</code>
     * @return The participationCount.
     */
    @java.lang.Override
    public int getParticipationCount() {
      return participationCount_;
    }
    /**
     * <code>int32 participation_count = 3;</code>
     * @param value The participationCount to set.
     * @return This builder for chaining.
     */
    public Builder setParticipationCount(int value) {
      
      participationCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 participation_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipationCount() {
      
      participationCount_ = 0;
      onChanged();
      return this;
    }

    private int engagementLevel_ ;
    /**
     * <code>int32 engagement_level = 4;</code>
     * @return The engagementLevel.
     */
    @java.lang.Override
    public int getEngagementLevel() {
      return engagementLevel_;
    }
    /**
     * <code>int32 engagement_level = 4;</code>
     * @param value The engagementLevel to set.
     * @return This builder for chaining.
     */
    public Builder setEngagementLevel(int value) {
      
      engagementLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 engagement_level = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEngagementLevel() {
      
      engagementLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 5;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 5;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 5;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartclassroom.EngagementResponse)
  }

  // @@protoc_insertion_point(class_scope:smartclassroom.EngagementResponse)
  private static final com.nci.smartclassroom.smartclassroomsystem.EngagementResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nci.smartclassroom.smartclassroomsystem.EngagementResponse();
  }

  public static com.nci.smartclassroom.smartclassroomsystem.EngagementResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EngagementResponse>
      PARSER = new com.google.protobuf.AbstractParser<EngagementResponse>() {
    @java.lang.Override
    public EngagementResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EngagementResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EngagementResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nci.smartclassroom.smartclassroomsystem.EngagementResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

