// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface EngagementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.EngagementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string class_id = 1;</code>
   * @return The classId.
   */
  java.lang.String getClassId();
  /**
   * <code>string class_id = 1;</code>
   * @return The bytes for classId.
   */
  com.google.protobuf.ByteString
      getClassIdBytes();

  /**
   * <code>string class_name = 2;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string class_name = 2;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();
}
