// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface EngagementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.EngagementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   * @return The studentId.
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   * @return The bytes for studentId.
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>double attention_score = 2;</code>
   * @return The attentionScore.
   */
  double getAttentionScore();

  /**
   * <code>int32 participation_count = 3;</code>
   * @return The participationCount.
   */
  int getParticipationCount();

  /**
   * <code>int32 engagement_level = 4;</code>
   * @return The engagementLevel.
   */
  int getEngagementLevel();

  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
