// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface GroupUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.GroupUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string update_type = 2;</code>
   * @return The updateType.
   */
  java.lang.String getUpdateType();
  /**
   * <code>string update_type = 2;</code>
   * @return The bytes for updateType.
   */
  com.google.protobuf.ByteString
      getUpdateTypeBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string sender = 4;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 4;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
