// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface ResourceSummaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.ResourceSummaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 items_available = 1;</code>
   * @return The itemsAvailable.
   */
  int getItemsAvailable();

  /**
   * <code>int32 items_pending = 2;</code>
   * @return The itemsPending.
   */
  int getItemsPending();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @return A list containing the fulfilledItems.
   */
  java.util.List<java.lang.String>
      getFulfilledItemsList();
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @return The count of fulfilledItems.
   */
  int getFulfilledItemsCount();
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @param index The index of the element to return.
   * @return The fulfilledItems at the given index.
   */
  java.lang.String getFulfilledItems(int index);
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fulfilledItems at the given index.
   */
  com.google.protobuf.ByteString
      getFulfilledItemsBytes(int index);
}
