// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

/**
 * Protobuf type {@code smartclassroom.ResourceSummaryResponse}
 */
public final class ResourceSummaryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartclassroom.ResourceSummaryResponse)
    ResourceSummaryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceSummaryResponse.newBuilder() to construct.
  private ResourceSummaryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceSummaryResponse() {
    message_ = "";
    fulfilledItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceSummaryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_ResourceSummaryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_ResourceSummaryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.class, com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.Builder.class);
  }

  public static final int ITEMS_AVAILABLE_FIELD_NUMBER = 1;
  private int itemsAvailable_;
  /**
   * <code>int32 items_available = 1;</code>
   * @return The itemsAvailable.
   */
  @java.lang.Override
  public int getItemsAvailable() {
    return itemsAvailable_;
  }

  public static final int ITEMS_PENDING_FIELD_NUMBER = 2;
  private int itemsPending_;
  /**
   * <code>int32 items_pending = 2;</code>
   * @return The itemsPending.
   */
  @java.lang.Override
  public int getItemsPending() {
    return itemsPending_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULFILLED_ITEMS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList fulfilledItems_;
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @return A list containing the fulfilledItems.
   */
  public com.google.protobuf.ProtocolStringList
      getFulfilledItemsList() {
    return fulfilledItems_;
  }
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @return The count of fulfilledItems.
   */
  public int getFulfilledItemsCount() {
    return fulfilledItems_.size();
  }
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @param index The index of the element to return.
   * @return The fulfilledItems at the given index.
   */
  public java.lang.String getFulfilledItems(int index) {
    return fulfilledItems_.get(index);
  }
  /**
   * <code>repeated string fulfilled_items = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fulfilledItems at the given index.
   */
  public com.google.protobuf.ByteString
      getFulfilledItemsBytes(int index) {
    return fulfilledItems_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (itemsAvailable_ != 0) {
      output.writeInt32(1, itemsAvailable_);
    }
    if (itemsPending_ != 0) {
      output.writeInt32(2, itemsPending_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    for (int i = 0; i < fulfilledItems_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fulfilledItems_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (itemsAvailable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, itemsAvailable_);
    }
    if (itemsPending_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, itemsPending_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < fulfilledItems_.size(); i++) {
        dataSize += computeStringSizeNoTag(fulfilledItems_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFulfilledItemsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse)) {
      return super.equals(obj);
    }
    com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse other = (com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse) obj;

    if (getItemsAvailable()
        != other.getItemsAvailable()) return false;
    if (getItemsPending()
        != other.getItemsPending()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getFulfilledItemsList()
        .equals(other.getFulfilledItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ITEMS_AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getItemsAvailable();
    hash = (37 * hash) + ITEMS_PENDING_FIELD_NUMBER;
    hash = (53 * hash) + getItemsPending();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getFulfilledItemsCount() > 0) {
      hash = (37 * hash) + FULFILLED_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getFulfilledItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartclassroom.ResourceSummaryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartclassroom.ResourceSummaryResponse)
      com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_ResourceSummaryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_ResourceSummaryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.class, com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.Builder.class);
    }

    // Construct using com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itemsAvailable_ = 0;

      itemsPending_ = 0;

      message_ = "";

      fulfilledItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_ResourceSummaryResponse_descriptor;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse getDefaultInstanceForType() {
      return com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse build() {
      com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse buildPartial() {
      com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse result = new com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse(this);
      int from_bitField0_ = bitField0_;
      result.itemsAvailable_ = itemsAvailable_;
      result.itemsPending_ = itemsPending_;
      result.message_ = message_;
      if (((bitField0_ & 0x00000001) != 0)) {
        fulfilledItems_ = fulfilledItems_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.fulfilledItems_ = fulfilledItems_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse) {
        return mergeFrom((com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse other) {
      if (other == com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse.getDefaultInstance()) return this;
      if (other.getItemsAvailable() != 0) {
        setItemsAvailable(other.getItemsAvailable());
      }
      if (other.getItemsPending() != 0) {
        setItemsPending(other.getItemsPending());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.fulfilledItems_.isEmpty()) {
        if (fulfilledItems_.isEmpty()) {
          fulfilledItems_ = other.fulfilledItems_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFulfilledItemsIsMutable();
          fulfilledItems_.addAll(other.fulfilledItems_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              itemsAvailable_ = input.readInt32();

              break;
            } // case 8
            case 16: {
              itemsPending_ = input.readInt32();

              break;
            } // case 16
            case 26: {
              message_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFulfilledItemsIsMutable();
              fulfilledItems_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int itemsAvailable_ ;
    /**
     * <code>int32 items_available = 1;</code>
     * @return The itemsAvailable.
     */
    @java.lang.Override
    public int getItemsAvailable() {
      return itemsAvailable_;
    }
    /**
     * <code>int32 items_available = 1;</code>
     * @param value The itemsAvailable to set.
     * @return This builder for chaining.
     */
    public Builder setItemsAvailable(int value) {
      
      itemsAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 items_available = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemsAvailable() {
      
      itemsAvailable_ = 0;
      onChanged();
      return this;
    }

    private int itemsPending_ ;
    /**
     * <code>int32 items_pending = 2;</code>
     * @return The itemsPending.
     */
    @java.lang.Override
    public int getItemsPending() {
      return itemsPending_;
    }
    /**
     * <code>int32 items_pending = 2;</code>
     * @param value The itemsPending to set.
     * @return This builder for chaining.
     */
    public Builder setItemsPending(int value) {
      
      itemsPending_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 items_pending = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemsPending() {
      
      itemsPending_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList fulfilledItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFulfilledItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fulfilledItems_ = new com.google.protobuf.LazyStringArrayList(fulfilledItems_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @return A list containing the fulfilledItems.
     */
    public com.google.protobuf.ProtocolStringList
        getFulfilledItemsList() {
      return fulfilledItems_.getUnmodifiableView();
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @return The count of fulfilledItems.
     */
    public int getFulfilledItemsCount() {
      return fulfilledItems_.size();
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param index The index of the element to return.
     * @return The fulfilledItems at the given index.
     */
    public java.lang.String getFulfilledItems(int index) {
      return fulfilledItems_.get(index);
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the fulfilledItems at the given index.
     */
    public com.google.protobuf.ByteString
        getFulfilledItemsBytes(int index) {
      return fulfilledItems_.getByteString(index);
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param index The index to set the value at.
     * @param value The fulfilledItems to set.
     * @return This builder for chaining.
     */
    public Builder setFulfilledItems(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFulfilledItemsIsMutable();
      fulfilledItems_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param value The fulfilledItems to add.
     * @return This builder for chaining.
     */
    public Builder addFulfilledItems(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFulfilledItemsIsMutable();
      fulfilledItems_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param values The fulfilledItems to add.
     * @return This builder for chaining.
     */
    public Builder addAllFulfilledItems(
        java.lang.Iterable<java.lang.String> values) {
      ensureFulfilledItemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, fulfilledItems_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFulfilledItems() {
      fulfilledItems_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string fulfilled_items = 4;</code>
     * @param value The bytes of the fulfilledItems to add.
     * @return This builder for chaining.
     */
    public Builder addFulfilledItemsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFulfilledItemsIsMutable();
      fulfilledItems_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartclassroom.ResourceSummaryResponse)
  }

  // @@protoc_insertion_point(class_scope:smartclassroom.ResourceSummaryResponse)
  private static final com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse();
  }

  public static com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceSummaryResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResourceSummaryResponse>() {
    @java.lang.Override
    public ResourceSummaryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceSummaryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceSummaryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nci.smartclassroom.smartclassroomsystem.ResourceSummaryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

