// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface ResourceCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.ResourceCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resource_name = 1;</code>
   * @return The resourceName.
   */
  java.lang.String getResourceName();
  /**
   * <code>string resource_name = 1;</code>
   * @return The bytes for resourceName.
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();

  /**
   * <code>string resource_type = 2;</code>
   * @return The resourceType.
   */
  java.lang.String getResourceType();
  /**
   * <code>string resource_type = 2;</code>
   * @return The bytes for resourceType.
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
