// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface ResourceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.ResourceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resource_id = 1;</code>
   * @return The resourceId.
   */
  java.lang.String getResourceId();
  /**
   * <code>string resource_id = 1;</code>
   * @return The bytes for resourceId.
   */
  com.google.protobuf.ByteString
      getResourceIdBytes();

  /**
   * <code>string resource_name = 2;</code>
   * @return The resourceName.
   */
  java.lang.String getResourceName();
  /**
   * <code>string resource_name = 2;</code>
   * @return The bytes for resourceName.
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string priority = 4;</code>
   * @return The priority.
   */
  java.lang.String getPriority();
  /**
   * <code>string priority = 4;</code>
   * @return The bytes for priority.
   */
  com.google.protobuf.ByteString
      getPriorityBytes();

  /**
   * <code>string requester_id = 5;</code>
   * @return The requesterId.
   */
  java.lang.String getRequesterId();
  /**
   * <code>string requester_id = 5;</code>
   * @return The bytes for requesterId.
   */
  com.google.protobuf.ByteString
      getRequesterIdBytes();
}
