// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface ResourceCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.ResourceCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   * @return The available.
   */
  boolean getAvailable();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string estimated_wait_time = 4;</code>
   * @return The estimatedWaitTime.
   */
  java.lang.String getEstimatedWaitTime();
  /**
   * <code>string estimated_wait_time = 4;</code>
   * @return The bytes for estimatedWaitTime.
   */
  com.google.protobuf.ByteString
      getEstimatedWaitTimeBytes();
}
