// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public final class SmartClassroomServiceImpl {
  private SmartClassroomServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_AttendanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_AttendanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_AttendanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_AttendanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_EngagementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_EngagementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_EngagementResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_EngagementResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_ResourceCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_ResourceCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_ResourceCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_ResourceCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_ResourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_ResourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_ResourceSummaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_ResourceSummaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_TutorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_TutorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_TutorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_TutorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_GroupMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_GroupMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartclassroom_GroupUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartclassroom_GroupUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025smart_classroom.proto\022\016smartclassroom\"" +
      "L\n\021AttendanceRequest\022\022\n\nstudent_id\030\001 \001(\t" +
      "\022\020\n\010class_id\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\"M\n" +
      "\022AttendanceResponse\022\017\n\007present\030\001 \001(\010\022\017\n\007" +
      "message\030\002 \001(\t\022\025\n\rrecorded_time\030\003 \001(\t\"9\n\021" +
      "EngagementRequest\022\020\n\010class_id\030\001 \001(\t\022\022\n\nc" +
      "lass_name\030\002 \001(\t\"\213\001\n\022EngagementResponse\022\022" +
      "\n\nstudent_id\030\001 \001(\t\022\027\n\017attention_score\030\002 " +
      "\001(\001\022\033\n\023participation_count\030\003 \001(\005\022\030\n\020enga" +
      "gement_level\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001(\t\"V\n" +
      "\024ResourceCheckRequest\022\025\n\rresource_name\030\001" +
      " \001(\t\022\025\n\rresource_type\030\002 \001(\t\022\020\n\010location\030" +
      "\003 \001(\t\"k\n\025ResourceCheckResponse\022\021\n\tavaila" +
      "ble\030\001 \001(\010\022\020\n\010quantity\030\002 \001(\005\022\020\n\010location\030" +
      "\003 \001(\t\022\033\n\023estimated_wait_time\030\004 \001(\t\"w\n\017Re" +
      "sourceRequest\022\023\n\013resource_id\030\001 \001(\t\022\025\n\rre" +
      "source_name\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\022\020\n\010p" +
      "riority\030\004 \001(\t\022\024\n\014requester_id\030\005 \001(\t\"s\n\027R" +
      "esourceSummaryResponse\022\027\n\017items_availabl" +
      "e\030\001 \001(\005\022\025\n\ritems_pending\030\002 \001(\005\022\017\n\007messag" +
      "e\030\003 \001(\t\022\027\n\017fulfilled_items\030\004 \003(\t\"X\n\014Tuto" +
      "rRequest\022\017\n\007subject\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t" +
      "\022\022\n\nstudent_id\030\003 \001(\t\022\024\n\014max_distance\030\004 \001" +
      "(\005\"\227\001\n\rTutorResponse\022\020\n\010tutor_id\030\001 \001(\t\022\014" +
      "\n\004name\030\002 \001(\t\022\021\n\texpertise\030\003 \001(\t\022\016\n\006ratin" +
      "g\030\004 \001(\001\022\032\n\022sessions_completed\030\005 \001(\005\022\021\n\ta" +
      "vailable\030\006 \001(\010\022\024\n\014contact_info\030\007 \001(\t\"n\n\014" +
      "GroupMessage\022\022\n\nstudent_id\030\001 \001(\t\022\020\n\010grou" +
      "p_id\030\002 \001(\t\022\024\n\014message_type\030\003 \001(\t\022\017\n\007cont" +
      "ent\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\t\"h\n\013GroupUpd" +
      "ate\022\020\n\010group_id\030\001 \001(\t\022\023\n\013update_type\030\002 \001" +
      "(\t\022\017\n\007message\030\003 \001(\t\022\016\n\006sender\030\004 \001(\t\022\021\n\tt" +
      "imestamp\030\005 \001(\t2\322\001\n\030StudentEngagementServ" +
      "ice\022X\n\017TrackAttendance\022!.smartclassroom." +
      "AttendanceRequest\032\".smartclassroom.Atten" +
      "danceResponse\022\\\n\021MonitorEngagement\022!.sma" +
      "rtclassroom.EngagementRequest\032\".smartcla" +
      "ssroom.EngagementResponse0\0012\340\001\n\024SmartRes" +
      "ourceService\022h\n\031CheckResourceAvailabilit" +
      "y\022$.smartclassroom.ResourceCheckRequest\032" +
      "%.smartclassroom.ResourceCheckResponse\022^" +
      "\n\020RequestResources\022\037.smartclassroom.Reso" +
      "urceRequest\032\'.smartclassroom.ResourceSum" +
      "maryResponse(\0012\271\001\n\024CollaborationService\022" +
      "J\n\tFindTutor\022\034.smartclassroom.TutorReque" +
      "st\032\035.smartclassroom.TutorResponse0\001\022U\n\024C" +
      "oordinateStudyGroup\022\034.smartclassroom.Gro" +
      "upMessage\032\033.smartclassroom.GroupUpdate(\001" +
      "0\001BJ\n+com.nci.smartclassroom.smartclassr" +
      "oomsystemB\031SmartClassroomServiceImplP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_smartclassroom_AttendanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartclassroom_AttendanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_AttendanceRequest_descriptor,
        new java.lang.String[] { "StudentId", "ClassId", "Timestamp", });
    internal_static_smartclassroom_AttendanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartclassroom_AttendanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_AttendanceResponse_descriptor,
        new java.lang.String[] { "Present", "Message", "RecordedTime", });
    internal_static_smartclassroom_EngagementRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartclassroom_EngagementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_EngagementRequest_descriptor,
        new java.lang.String[] { "ClassId", "ClassName", });
    internal_static_smartclassroom_EngagementResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartclassroom_EngagementResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_EngagementResponse_descriptor,
        new java.lang.String[] { "StudentId", "AttentionScore", "ParticipationCount", "EngagementLevel", "Timestamp", });
    internal_static_smartclassroom_ResourceCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_smartclassroom_ResourceCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_ResourceCheckRequest_descriptor,
        new java.lang.String[] { "ResourceName", "ResourceType", "Location", });
    internal_static_smartclassroom_ResourceCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_smartclassroom_ResourceCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_ResourceCheckResponse_descriptor,
        new java.lang.String[] { "Available", "Quantity", "Location", "EstimatedWaitTime", });
    internal_static_smartclassroom_ResourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_smartclassroom_ResourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_ResourceRequest_descriptor,
        new java.lang.String[] { "ResourceId", "ResourceName", "Quantity", "Priority", "RequesterId", });
    internal_static_smartclassroom_ResourceSummaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_smartclassroom_ResourceSummaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_ResourceSummaryResponse_descriptor,
        new java.lang.String[] { "ItemsAvailable", "ItemsPending", "Message", "FulfilledItems", });
    internal_static_smartclassroom_TutorRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_smartclassroom_TutorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_TutorRequest_descriptor,
        new java.lang.String[] { "Subject", "Topic", "StudentId", "MaxDistance", });
    internal_static_smartclassroom_TutorResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_smartclassroom_TutorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_TutorResponse_descriptor,
        new java.lang.String[] { "TutorId", "Name", "Expertise", "Rating", "SessionsCompleted", "Available", "ContactInfo", });
    internal_static_smartclassroom_GroupMessage_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_smartclassroom_GroupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_GroupMessage_descriptor,
        new java.lang.String[] { "StudentId", "GroupId", "MessageType", "Content", "Timestamp", });
    internal_static_smartclassroom_GroupUpdate_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_smartclassroom_GroupUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartclassroom_GroupUpdate_descriptor,
        new java.lang.String[] { "GroupId", "UpdateType", "Message", "Sender", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
