// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

public interface TutorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartclassroom.TutorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tutor_id = 1;</code>
   * @return The tutorId.
   */
  java.lang.String getTutorId();
  /**
   * <code>string tutor_id = 1;</code>
   * @return The bytes for tutorId.
   */
  com.google.protobuf.ByteString
      getTutorIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string expertise = 3;</code>
   * @return The expertise.
   */
  java.lang.String getExpertise();
  /**
   * <code>string expertise = 3;</code>
   * @return The bytes for expertise.
   */
  com.google.protobuf.ByteString
      getExpertiseBytes();

  /**
   * <code>double rating = 4;</code>
   * @return The rating.
   */
  double getRating();

  /**
   * <code>int32 sessions_completed = 5;</code>
   * @return The sessionsCompleted.
   */
  int getSessionsCompleted();

  /**
   * <code>bool available = 6;</code>
   * @return The available.
   */
  boolean getAvailable();

  /**
   * <code>string contact_info = 7;</code>
   * @return The contactInfo.
   */
  java.lang.String getContactInfo();
  /**
   * <code>string contact_info = 7;</code>
   * @return The bytes for contactInfo.
   */
  com.google.protobuf.ByteString
      getContactInfoBytes();
}
