// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_classroom.proto

package com.nci.smartclassroom.smartclassroomsystem;

/**
 * Protobuf type {@code smartclassroom.TutorResponse}
 */
public final class TutorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartclassroom.TutorResponse)
    TutorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TutorResponse.newBuilder() to construct.
  private TutorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TutorResponse() {
    tutorId_ = "";
    name_ = "";
    expertise_ = "";
    contactInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TutorResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_TutorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_TutorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nci.smartclassroom.smartclassroomsystem.TutorResponse.class, com.nci.smartclassroom.smartclassroomsystem.TutorResponse.Builder.class);
  }

  public static final int TUTOR_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object tutorId_;
  /**
   * <code>string tutor_id = 1;</code>
   * @return The tutorId.
   */
  @java.lang.Override
  public java.lang.String getTutorId() {
    java.lang.Object ref = tutorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tutorId_ = s;
      return s;
    }
  }
  /**
   * <code>string tutor_id = 1;</code>
   * @return The bytes for tutorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTutorIdBytes() {
    java.lang.Object ref = tutorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tutorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERTISE_FIELD_NUMBER = 3;
  private volatile java.lang.Object expertise_;
  /**
   * <code>string expertise = 3;</code>
   * @return The expertise.
   */
  @java.lang.Override
  public java.lang.String getExpertise() {
    java.lang.Object ref = expertise_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      expertise_ = s;
      return s;
    }
  }
  /**
   * <code>string expertise = 3;</code>
   * @return The bytes for expertise.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExpertiseBytes() {
    java.lang.Object ref = expertise_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      expertise_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATING_FIELD_NUMBER = 4;
  private double rating_;
  /**
   * <code>double rating = 4;</code>
   * @return The rating.
   */
  @java.lang.Override
  public double getRating() {
    return rating_;
  }

  public static final int SESSIONS_COMPLETED_FIELD_NUMBER = 5;
  private int sessionsCompleted_;
  /**
   * <code>int32 sessions_completed = 5;</code>
   * @return The sessionsCompleted.
   */
  @java.lang.Override
  public int getSessionsCompleted() {
    return sessionsCompleted_;
  }

  public static final int AVAILABLE_FIELD_NUMBER = 6;
  private boolean available_;
  /**
   * <code>bool available = 6;</code>
   * @return The available.
   */
  @java.lang.Override
  public boolean getAvailable() {
    return available_;
  }

  public static final int CONTACT_INFO_FIELD_NUMBER = 7;
  private volatile java.lang.Object contactInfo_;
  /**
   * <code>string contact_info = 7;</code>
   * @return The contactInfo.
   */
  @java.lang.Override
  public java.lang.String getContactInfo() {
    java.lang.Object ref = contactInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contactInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string contact_info = 7;</code>
   * @return The bytes for contactInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContactInfoBytes() {
    java.lang.Object ref = contactInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contactInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tutorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tutorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expertise_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, expertise_);
    }
    if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
      output.writeDouble(4, rating_);
    }
    if (sessionsCompleted_ != 0) {
      output.writeInt32(5, sessionsCompleted_);
    }
    if (available_ != false) {
      output.writeBool(6, available_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contactInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contactInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tutorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tutorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(expertise_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, expertise_);
    }
    if (java.lang.Double.doubleToRawLongBits(rating_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, rating_);
    }
    if (sessionsCompleted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, sessionsCompleted_);
    }
    if (available_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, available_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contactInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contactInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nci.smartclassroom.smartclassroomsystem.TutorResponse)) {
      return super.equals(obj);
    }
    com.nci.smartclassroom.smartclassroomsystem.TutorResponse other = (com.nci.smartclassroom.smartclassroomsystem.TutorResponse) obj;

    if (!getTutorId()
        .equals(other.getTutorId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getExpertise()
        .equals(other.getExpertise())) return false;
    if (java.lang.Double.doubleToLongBits(getRating())
        != java.lang.Double.doubleToLongBits(
            other.getRating())) return false;
    if (getSessionsCompleted()
        != other.getSessionsCompleted()) return false;
    if (getAvailable()
        != other.getAvailable()) return false;
    if (!getContactInfo()
        .equals(other.getContactInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TUTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTutorId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EXPERTISE_FIELD_NUMBER;
    hash = (53 * hash) + getExpertise().hashCode();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRating()));
    hash = (37 * hash) + SESSIONS_COMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + getSessionsCompleted();
    hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAvailable());
    hash = (37 * hash) + CONTACT_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getContactInfo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nci.smartclassroom.smartclassroomsystem.TutorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartclassroom.TutorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartclassroom.TutorResponse)
      com.nci.smartclassroom.smartclassroomsystem.TutorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_TutorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_TutorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nci.smartclassroom.smartclassroomsystem.TutorResponse.class, com.nci.smartclassroom.smartclassroomsystem.TutorResponse.Builder.class);
    }

    // Construct using com.nci.smartclassroom.smartclassroomsystem.TutorResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tutorId_ = "";

      name_ = "";

      expertise_ = "";

      rating_ = 0D;

      sessionsCompleted_ = 0;

      available_ = false;

      contactInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nci.smartclassroom.smartclassroomsystem.SmartClassroomServiceImpl.internal_static_smartclassroom_TutorResponse_descriptor;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.TutorResponse getDefaultInstanceForType() {
      return com.nci.smartclassroom.smartclassroomsystem.TutorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.TutorResponse build() {
      com.nci.smartclassroom.smartclassroomsystem.TutorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nci.smartclassroom.smartclassroomsystem.TutorResponse buildPartial() {
      com.nci.smartclassroom.smartclassroomsystem.TutorResponse result = new com.nci.smartclassroom.smartclassroomsystem.TutorResponse(this);
      result.tutorId_ = tutorId_;
      result.name_ = name_;
      result.expertise_ = expertise_;
      result.rating_ = rating_;
      result.sessionsCompleted_ = sessionsCompleted_;
      result.available_ = available_;
      result.contactInfo_ = contactInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nci.smartclassroom.smartclassroomsystem.TutorResponse) {
        return mergeFrom((com.nci.smartclassroom.smartclassroomsystem.TutorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nci.smartclassroom.smartclassroomsystem.TutorResponse other) {
      if (other == com.nci.smartclassroom.smartclassroomsystem.TutorResponse.getDefaultInstance()) return this;
      if (!other.getTutorId().isEmpty()) {
        tutorId_ = other.tutorId_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getExpertise().isEmpty()) {
        expertise_ = other.expertise_;
        onChanged();
      }
      if (other.getRating() != 0D) {
        setRating(other.getRating());
      }
      if (other.getSessionsCompleted() != 0) {
        setSessionsCompleted(other.getSessionsCompleted());
      }
      if (other.getAvailable() != false) {
        setAvailable(other.getAvailable());
      }
      if (!other.getContactInfo().isEmpty()) {
        contactInfo_ = other.contactInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tutorId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              expertise_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 33: {
              rating_ = input.readDouble();

              break;
            } // case 33
            case 40: {
              sessionsCompleted_ = input.readInt32();

              break;
            } // case 40
            case 48: {
              available_ = input.readBool();

              break;
            } // case 48
            case 58: {
              contactInfo_ = input.readStringRequireUtf8();

              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object tutorId_ = "";
    /**
     * <code>string tutor_id = 1;</code>
     * @return The tutorId.
     */
    public java.lang.String getTutorId() {
      java.lang.Object ref = tutorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tutorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tutor_id = 1;</code>
     * @return The bytes for tutorId.
     */
    public com.google.protobuf.ByteString
        getTutorIdBytes() {
      java.lang.Object ref = tutorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tutorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tutor_id = 1;</code>
     * @param value The tutorId to set.
     * @return This builder for chaining.
     */
    public Builder setTutorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tutorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tutor_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTutorId() {
      
      tutorId_ = getDefaultInstance().getTutorId();
      onChanged();
      return this;
    }
    /**
     * <code>string tutor_id = 1;</code>
     * @param value The bytes for tutorId to set.
     * @return This builder for chaining.
     */
    public Builder setTutorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tutorId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object expertise_ = "";
    /**
     * <code>string expertise = 3;</code>
     * @return The expertise.
     */
    public java.lang.String getExpertise() {
      java.lang.Object ref = expertise_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expertise_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string expertise = 3;</code>
     * @return The bytes for expertise.
     */
    public com.google.protobuf.ByteString
        getExpertiseBytes() {
      java.lang.Object ref = expertise_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expertise_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string expertise = 3;</code>
     * @param value The expertise to set.
     * @return This builder for chaining.
     */
    public Builder setExpertise(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      expertise_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string expertise = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpertise() {
      
      expertise_ = getDefaultInstance().getExpertise();
      onChanged();
      return this;
    }
    /**
     * <code>string expertise = 3;</code>
     * @param value The bytes for expertise to set.
     * @return This builder for chaining.
     */
    public Builder setExpertiseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      expertise_ = value;
      onChanged();
      return this;
    }

    private double rating_ ;
    /**
     * <code>double rating = 4;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
      return rating_;
    }
    /**
     * <code>double rating = 4;</code>
     * @param value The rating to set.
     * @return This builder for chaining.
     */
    public Builder setRating(double value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rating = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRating() {
      
      rating_ = 0D;
      onChanged();
      return this;
    }

    private int sessionsCompleted_ ;
    /**
     * <code>int32 sessions_completed = 5;</code>
     * @return The sessionsCompleted.
     */
    @java.lang.Override
    public int getSessionsCompleted() {
      return sessionsCompleted_;
    }
    /**
     * <code>int32 sessions_completed = 5;</code>
     * @param value The sessionsCompleted to set.
     * @return This builder for chaining.
     */
    public Builder setSessionsCompleted(int value) {
      
      sessionsCompleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sessions_completed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionsCompleted() {
      
      sessionsCompleted_ = 0;
      onChanged();
      return this;
    }

    private boolean available_ ;
    /**
     * <code>bool available = 6;</code>
     * @return The available.
     */
    @java.lang.Override
    public boolean getAvailable() {
      return available_;
    }
    /**
     * <code>bool available = 6;</code>
     * @param value The available to set.
     * @return This builder for chaining.
     */
    public Builder setAvailable(boolean value) {
      
      available_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool available = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailable() {
      
      available_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object contactInfo_ = "";
    /**
     * <code>string contact_info = 7;</code>
     * @return The contactInfo.
     */
    public java.lang.String getContactInfo() {
      java.lang.Object ref = contactInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contact_info = 7;</code>
     * @return The bytes for contactInfo.
     */
    public com.google.protobuf.ByteString
        getContactInfoBytes() {
      java.lang.Object ref = contactInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contact_info = 7;</code>
     * @param value The contactInfo to set.
     * @return This builder for chaining.
     */
    public Builder setContactInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contactInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contact_info = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContactInfo() {
      
      contactInfo_ = getDefaultInstance().getContactInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string contact_info = 7;</code>
     * @param value The bytes for contactInfo to set.
     * @return This builder for chaining.
     */
    public Builder setContactInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contactInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartclassroom.TutorResponse)
  }

  // @@protoc_insertion_point(class_scope:smartclassroom.TutorResponse)
  private static final com.nci.smartclassroom.smartclassroomsystem.TutorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nci.smartclassroom.smartclassroomsystem.TutorResponse();
  }

  public static com.nci.smartclassroom.smartclassroomsystem.TutorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TutorResponse>
      PARSER = new com.google.protobuf.AbstractParser<TutorResponse>() {
    @java.lang.Override
    public TutorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TutorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TutorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nci.smartclassroom.smartclassroomsystem.TutorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

